on:
  push:
    branches:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      # checkout code
      - uses: actions/checkout@v4

      # authenticate with GCP with workload identity provider
      - uses: 'google-github-actions/auth@v2'
        id: auth
        name: Authenticate to GCP
        with:
          project_id: 'cloud-agent-457418' # update with project ID
          workload_identity_provider: 'projects/417926879009/locations/global/workloadIdentityPools/github/providers/my-repo'

        # configure/login with docker
      - name: gcloud Configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

        # setup docker buildx
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      # build and push the image
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: us-central1-docker.pkg.dev/cloud-agent-457418/cloud-final/app:v1

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy cloud-final \
          --allow-unauthenticated \
          --image us-central1-docker.pkg.dev/cloud-agent-457418/cloud-final/app:v1 \
          --service-account syl-sum@cloud-agent-457418.iam.gserviceaccount.com \
          --region us-central1 \
          --port 8000
